// Question types an instructor can pick. `mode` is the default answer behaviour:
//  - self_check : question on front, flip to see the answer, then mark ✔ / ✖ yourself
//  - judge_first: statement on front, choose ✔ / ✖ first, the flip reveals if you were right
export const CARD_TYPES = [
  {
    value: 'translation',
    label: 'Translation recall',
    mode: 'self_check',
    front: 'Word or phrase',
    frontHint: 'der Apfel',
    back: 'Meaning',
    backHint: 'the apple',
  },
  {
    value: 'picture_word',
    label: 'Picture to word',
    mode: 'self_check',
    front: 'Prompt (add an image below)',
    frontHint: 'What is this called?',
    back: 'The word, with a sample sentence',
    backHint: 'der Hund — Der Hund schläft.',
  },
  {
    value: 'fill_blank',
    label: 'Fill in the blank',
    mode: 'self_check',
    front: 'Sentence with a gap',
    frontHint: 'Ich ___ aus Kenia. (kommen)',
    back: 'The missing word',
    backHint: 'komme',
  },
  {
    value: 'correct_incorrect',
    label: 'Correct or incorrect',
    mode: 'judge_first',
    front: 'Sentence to judge',
    frontHint: 'Ich habe gestern ins Kino gegangen.',
    back: 'Corrected form',
    backHint: 'Ich bin gestern ins Kino gegangen.',
  },
  {
    value: 'conjugation',
    label: 'Conjugation or tense',
    mode: 'self_check',
    front: 'Verb + pronoun + tense',
    frontHint: 'gehen · wir · Präteritum',
    back: 'Correct form',
    backHint: 'gingen',
  },
  {
    value: 'odd_one_out',
    label: 'Odd one out',
    mode: 'self_check',
    front: 'Four words',
    frontHint: 'Montag · Dienstag · Mai · Freitag',
    back: 'The odd one and why',
    backHint: 'Mai — a month, the rest are weekdays',
  },
  {
    value: 'idiom',
    label: 'Idiom or proverb',
    mode: 'self_check',
    front: 'The expression',
    frontHint: 'Ich verstehe nur Bahnhof.',
    back: 'Meaning and when to use it',
    backHint: "I don't understand a thing.",
  },
  {
    value: 'synonym_antonym',
    label: 'Synonym or antonym',
    mode: 'self_check',
    front: 'A word and a prompt',
    frontHint: 'Opposite of: groß',
    back: 'The matching word',
    backHint: 'klein',
  },
  {
    value: 'word_order',
    label: 'Word order',
    mode: 'self_check',
    front: 'Scrambled words',
    frontHint: 'gern / Ich / Fußball / spiele',
    back: 'The correct sentence',
    backHint: 'Ich spiele gern Fußball.',
  },
  {
    value: 'say_aloud',
    label: 'Say it aloud',
    mode: 'self_check',
    front: 'Word or phrase to speak',
    frontHint: 'Entschuldigung',
    back: 'Pronunciation guide and meaning',
    backHint: 'ent-SHUL-dee-goong — excuse me',
  },
  {
    value: 'article_gender',
    label: 'Article or gender',
    mode: 'self_check',
    front: 'A noun',
    frontHint: 'Mädchen',
    back: 'Article + noun',
    backHint: 'das Mädchen',
  },
];

export const typeMeta = (value) => CARD_TYPES.find((t) => t.value === value) ?? CARD_TYPES[0];
